// Code generated by tools/genevents. DO NOT EDIT.

package events

import (
	"errors"
	"fmt"
	"time"
)

// DashboardRetried is emitted when a dashboard operation transitions to retried.
type DashboardRetried struct {
	TenantID     string
	SessionID    string
	ResourceID   string
	Region       string
	OccurredAt   time.Time
	DurationMs   int64
	AttemptCount int
	BytesIn      int64
	BytesOut     int64
	StatusCode   int
	Message      string
	Labels       map[string]string
}

func (e *DashboardRetried) EventName() string { return "dashboard.retried" }

func (e *DashboardRetried) Validate() error {
	if e.TenantID == "" {
		return errors.New("dashboard.retried: tenant id is required")
	}
	if e.OccurredAt.IsZero() {
		return errors.New("dashboard.retried: occurred-at timestamp is required")
	}
	if e.OccurredAt.After(time.Now().Add(5 * time.Minute)) {
		return fmt.Errorf("dashboard.retried: occurred-at %s is in the future", e.OccurredAt)
	}
	if e.DurationMs < 0 {
		return fmt.Errorf("dashboard.retried: negative duration %d", e.DurationMs)
	}
	if e.AttemptCount < 0 {
		return fmt.Errorf("dashboard.retried: negative attempt count %d", e.AttemptCount)
	}
	if e.BytesIn < 0 || e.BytesOut < 0 {
		return errors.New("dashboard.retried: negative byte counts")
	}
	if e.StatusCode != 0 && (e.StatusCode < 100 || e.StatusCode > 599) {
		return fmt.Errorf("dashboard.retried: implausible status code %d", e.StatusCode)
	}
	for k, v := range e.Labels {
		if k == "" {
			return errors.New("dashboard.retried: empty label key")
		}
		if len(v) > 256 {
			return fmt.Errorf("dashboard.retried: label %q exceeds 256 bytes", k)
		}
	}
	return nil
}

func (e *DashboardRetried) Fields() map[string]any {
	fields := map[string]any{
		"event":         e.EventName(),
		"tenant_id":     e.TenantID,
		"session_id":    e.SessionID,
		"resource_id":   e.ResourceID,
		"region":        e.Region,
		"occurred_at":   e.OccurredAt,
		"duration_ms":   e.DurationMs,
		"attempt_count": e.AttemptCount,
		"bytes_in":      e.BytesIn,
		"bytes_out":     e.BytesOut,
		"status_code":   e.StatusCode,
		"message":       e.Message,
	}
	for k, v := range e.Labels {
		fields["label."+k] = v
	}
	return fields
}

func init() {
	register("dashboard.retried", func() Event { return &DashboardRetried{} })
}
