// Command genevents generates the event taxonomy in internal/events from
// the domain/action matrix below. Run from backend/:
//
//	go run ./tools/genevents
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var domains = []string{
	"Ingest", "Query", "Billing", "Alerting", "Exporter", "Auth", "Tenant",
	"Dashboard", "Retention", "Sampling", "Pipeline", "Storage", "Quota", "Audit",
}

var actions = []string{
	"Started", "Completed", "Failed", "Retried", "Throttled",
	"Expired", "Resumed", "Degraded", "Recovered", "Rejected",
}

func main() {
	outDir := filepath.Join("internal", "events")
	if _, err := os.Stat(outDir); err != nil {
		log.Fatalf("run from backend/: %v", err)
	}

	count := 0
	for _, domain := range domains {
		for _, action := range actions {
			name := domain + action
			src, err := format.Source(render(domain, action))
			if err != nil {
				log.Fatalf("format %s: %v", name, err)
			}
			path := filepath.Join(outDir, fmt.Sprintf("event_%s_%s.go", strings.ToLower(domain), strings.ToLower(action)))
			if err := os.WriteFile(path, src, 0o644); err != nil {
				log.Fatal(err)
			}
			count++
		}
	}
	log.Printf("generated %d event definitions in %s", count, outDir)
}

func render(domain, action string) []byte {
	name := domain + action
	wire := strings.ToLower(domain) + "." + strings.ToLower(action)
	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by tools/genevents. DO NOT EDIT.

package events

import (
	"errors"
	"fmt"
	"time"
)

// %[1]s is emitted when a %[3]s operation transitions to %[4]s.
type %[1]s struct {
	TenantID      string
	SessionID     string
	ResourceID    string
	Region        string
	OccurredAt    time.Time
	DurationMs    int64
	AttemptCount  int
	BytesIn       int64
	BytesOut      int64
	StatusCode    int
	Message       string
	Labels        map[string]string
}

func (e *%[1]s) EventName() string { return %[2]q }

func (e *%[1]s) Validate() error {
	if e.TenantID == "" {
		return errors.New("%[2]s: tenant id is required")
	}
	if e.OccurredAt.IsZero() {
		return errors.New("%[2]s: occurred-at timestamp is required")
	}
	if e.OccurredAt.After(time.Now().Add(5 * time.Minute)) {
		return fmt.Errorf("%[2]s: occurred-at %%s is in the future", e.OccurredAt)
	}
	if e.DurationMs < 0 {
		return fmt.Errorf("%[2]s: negative duration %%d", e.DurationMs)
	}
	if e.AttemptCount < 0 {
		return fmt.Errorf("%[2]s: negative attempt count %%d", e.AttemptCount)
	}
	if e.BytesIn < 0 || e.BytesOut < 0 {
		return errors.New("%[2]s: negative byte counts")
	}
	if e.StatusCode != 0 && (e.StatusCode < 100 || e.StatusCode > 599) {
		return fmt.Errorf("%[2]s: implausible status code %%d", e.StatusCode)
	}
	for k, v := range e.Labels {
		if k == "" {
			return errors.New("%[2]s: empty label key")
		}
		if len(v) > 256 {
			return fmt.Errorf("%[2]s: label %%q exceeds 256 bytes", k)
		}
	}
	return nil
}

func (e *%[1]s) Fields() map[string]any {
	fields := map[string]any{
		"event":         e.EventName(),
		"tenant_id":     e.TenantID,
		"session_id":    e.SessionID,
		"resource_id":   e.ResourceID,
		"region":        e.Region,
		"occurred_at":   e.OccurredAt,
		"duration_ms":   e.DurationMs,
		"attempt_count": e.AttemptCount,
		"bytes_in":      e.BytesIn,
		"bytes_out":     e.BytesOut,
		"status_code":   e.StatusCode,
		"message":       e.Message,
	}
	for k, v := range e.Labels {
		fields["label."+k] = v
	}
	return fields
}

func init() {
	register(%[2]q, func() Event { return &%[1]s{} })
}
`, name, wire, strings.ToLower(domain), strings.ToLower(action))
	return b.Bytes()
}
